version: "2"

run:
  timeout: 5m
  build-tags:
    - e2e

linters:
  default: standard
  enable:
    - errorlint
    - misspell
    - revive
  settings:
    revive:
      rules:
        - name: exported
          disabled: true

formatters:
  enable:
    - gofmt
    - goimports
